In [18]:
import numpy as np
import pandas as pd
import seaborn as sns

In [19]:
a=[[1,2],[2,2],[3,3],[4,5],[4,6]]
b=['X','Y']
c = pd.DataFrame(a,columns = b)
c

X  Y
0  1  2
1  2  2
2  3  3
3  4  5
4  4  6

In [20]:
np.var(c)

X    1.36
Y    2.64
dtype: float64

In [21]:
p = np.array([[0.8,0.6],[ -0.6,0.8]])
p

array([[ 0.8,  0.6],
       [-0.6,  0.8]])

In [22]:
pI= np.linalg.inv(p)
pI

array([[ 0.8, -0.6],
       [ 0.6,  0.8]])

In [23]:
#Now let's perform the basis transformation.
#We need to multiply pI by each vector in the dataframe c.
C= pI @ c.T
C.T

0    1
0 -0.4  2.2
1  0.4  2.8
2  0.6  4.2
3  0.2  6.4
4 -0.4  7.2

In [24]:
np.var(C.T)

0    0.1696
1    3.8304
dtype: float64

In [25]:
# SVD with food rating
ass = pd.read_csv("MyFoodRatings.csv")
ass.head(10)

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0    A        5       5       5         0            0     0      0      0   
1    B        4       4       4         0            0     0      0      0   
2    C        3       3       3         0            0     0      0      0   
3    D        2       2       2         0            0     0      0      0   
4    E        0       0       0         2            2     2      0      0   
5    F        0       0       0         1            1     1      0      0   
6    G        0       0       0         5            3     4      0      0   
7    H        0       0       0         4            4     4      0      0   
8    I        0       0       0         0            0     0      2      2   
9    J        0       0       0         0            0     0      1      1   

   Tempura  
0        0  
1        0  
2        0  
3        0  
4        0  
5        0  
6        0  
7        0  
8        4  
9        1

In [26]:
ass = ass.drop("Name",axis=1)

In [27]:
ass

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         4       4       4         0            0     0      0      0   
2         3       3       3         0            0     0      0      0   
3         2       2       2         0            0     0      0      0   
4         0       0       0         2            2     2      0      0   
5         0       0       0         1            1     1      0      0   
6         0       0       0         5            3     4      0      0   
7         0       0       0         4            4     4      0      0   
8         0       0       0         0            0     0      2      2   
9         0       0       0         0            0     0      1      1   
10        0       0       0         0            0     0      3      4   
11        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [28]:
U, s, VT = np.linalg.svd(ass, full_matrices=True)

In [30]:
U

array([[-6.80413817e-01,  0.00000000e+00,  0.00000000e+00,
         2.58908743e-33,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.83951720e-01, -2.63148402e-01,
         1.45752665e-18,  0.00000000e+00,  0.00000000e+00],
       [-5.44331054e-01,  4.96506831e-17,  3.85856584e-18,
        -1.78352620e-17,  2.48253415e-16,  8.15015983e-17,
        -4.42281885e-01, -2.92767967e-01,  6.46521942e-01,
        -1.62440512e-02,  5.53840102e-02, -3.24881025e-02],
       [-4.08248290e-01,  4.38559108e-33,  3.19773868e-34,
        -7.06645285e-34,  1.21871670e-32,  3.18417792e-33,
        -4.79822791e-17, -6.51972922e-01, -6.38955900e-01,
        -1.00346663e-18,  4.00753524e-18, -1.59750734e-18],
       [-2.72165527e-01, -9.93013661e-17, -7.71713167e-18,
         3.56705241e-17, -4.96506831e-16, -1.63003197e-16,
         8.84563769e-01, -1.46383983e-01,  3.23260971e-01,
         3.24881025e-02, -1.10768020e-01,  6.49762050e-02],
       [ 0.00000000e+00, -3.26217015e-01, -5.1838711

In [31]:
VT.shape

(9, 9)

In [33]:
print(s)

[1.27279221e+01 1.05770379e+01 8.84826058e+00 1.24205263e+00
 1.06125858e+00 4.06927550e-01 5.43862610e-16 3.23597471e-16
 2.65957113e-32]


In [36]:
setvec = np.array([[1,2,3],[-2,4,-2]])
round(np.dot(setvec[0],setvec[1]))

0